/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_antroid_check_CheckSum */

#ifndef _Included_com_antroid_check_CheckSum
#define _Included_com_antroid_check_CheckSum
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_antroid_check_CheckSum
 * Method:    CalculateJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_smit_com_factorytest_CheckSumActivity_CalculateJni
  (JNIEnv *, jobject);

/*
 * Class:     com_antroid_check_CheckSum
 * Method:    setFileName
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_smit_com_factorytest_CheckSumActivity_setFileName
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
